// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgxcyyipmunovgyomcci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZneGN5eWlwbXVub3ZneW9tY2NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODk5MzgsImV4cCI6MjA2NTU2NTkzOH0.XtAVe4bhz-8ZCbe_x5ZSd-kmdoAGRg-qOpysoXxLops";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);